# Generated by Django 6.1 on 2026-09-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participacion',
            constraint=models.UniqueConstraint(fields=('mascota', 'categoria'), name='una_participacion_por_mascota_categoria'),
        ),
    ]
